apiVersion: skaffold/v2beta10
kind: Config

build:
  artifacts:
    - image: website
      context: charts/website

deploy:
  helm:
    releases:
      - name: website
        chartPath: charts/website
        artifactOverrides:
          image: website

  kubectl:
    manifests:
      - https://download.elastic.co/downloads/eck/1.3.1/all-in-one.yaml
      - k8s/dev/*

profiles:
  - name: prod
    patches:
      - op: replace
        path: /deploy/kubectl/manifests/1
        value: k8s/prod/*
  - name: filebeat
    patches:
      - op: add
        path: /deploy/kubectl/manifests
        value:
          - k8s/filebeat/*
  - name: no-website
    patches:
      - op: remove
        path: /deploy/helm
