apiVersion: skaffold/v2beta10
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  - resourceType: Service
    resourceName: quickstart-kb-http
    port: 5601
    localPort: 5601
