apiVersion: skaffold/v2beta10
kind: Config

build:
  artifacts:
    - image: website
      context: charts/website

  kubectl:
    manifests:
      - https://download.elastic.co/downloads/eck/1.3.1/all-in-one.yaml
      - k8s/dev/*.yaml

profiles:
  - name: prod
    patches:
      - op: replace
        path: /deploy/kubectl/manifests
        value:
          - https://download.elastic.co/downloads/eck/1.3.1/all-in-one.yaml
          - k8s/prod/*.yaml
  - name: filebeat
    patches:
      - op: add
        path: /deploy/kubectl/manifests
        value:
          - k8s/filebeat/*

portForward:
  - resourceType: Service
    resourceName: quickstart-kb-http
    port: 5601
    localPort: 5601
    namespace: default
