apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: website
